### ISSUE TITLE
WAF doesn't allow to associate 10 or more rules 

### ISSUE THREAD

**Issue by elheim** [perfectsense/gyro#413] opened 2024-07-31 21:13 UTC
**Describe the bug**
When I'm trying to add 10th rule to `aws::wafv2-web-acl`, I'm getting an error `rule: Size of the collection must be less than or equal to 10`

**To Reproduce**
1. Create wafv2-web-acl
2. Add 10 or more rules 
3. Get an error from above

Perhaps this rule is connected to AWS's rule, that there're only 10 or less rate-based rules per rule group are allowed.

**Expected behavior**
I would expect `gyro` to allow me to create rules, if they aren't rate based, since this is not part of the [quote](https://docs.aws.amazon.com/waf/latest/developerguide/limits.html). For this case, I was able to create a rule through cli

**Stacktrace**
`aws::wafv2-web-acl`, I'm getting an error `rule: Size of the collection must be less than or equal to 10`

**Additional context**

**Comment by deepanjan90** [comment] 2024-09-05 14:28
duplicate of https://github.com/perfectsense/gyro-aws-provider/issues/656

**Closed as completed by deepanjan90** 2024-09-05 14:28 UTC
